# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu095-ffva2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/seshan/6.111_final_project/base/fpga/top_level.cache/wt [current_project]
set_property parent.project_path /home/seshan/6.111_final_project/base/fpga/top_level.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/seshan/6.111_final_project/base/fpga/top_level.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/seshan/6.111_final_project/base/hdl/bfis.sv
  /home/seshan/6.111_final_project/base/hdl/checked.sv
  /home/seshan/6.111_final_project/base/hdl/distance_calc.sv
  /home/seshan/6.111_final_project/base/hdl/fifo.sv
  /home/seshan/6.111_final_project/base/hdl/graph_fetch.sv
  /home/seshan/6.111_final_project/base/hdl/storage.sv
  /home/seshan/6.111_final_project/base/hdl/visited.sv
  /home/seshan/6.111_final_project/base/hdl/top_level.sv
}
read_verilog -library xil_defaultlib {
  /home/seshan/6.111_final_project/base/hdl/xilinx_single_port_ram_read_first.v
  /home/seshan/6.111_final_project/base/hdl/xilinx_true_dual_port_read_first_2_clock_ram.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/seshan/6.111_final_project/base/xdc/top_level.xdc
set_property used_in_implementation false [get_files /home/seshan/6.111_final_project/base/xdc/top_level.xdc]


synth_design -top top_level -part xcvu095-ffva2104-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
