# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sanjay/Documents/6.111/lab08/project_2/project_2.srcs/sources_1/ip/multiplier/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sanjay/Documents/6.111/lab08/project_2/project_2.gen/sources_1/ip/multiplier/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sanjay/Documents/6.111/lab08/project_2/project_2.srcs/sources_1/ip/multiplier/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sanjay/Documents/6.111/lab08/project_2/project_2.gen/sources_1/ip/multiplier/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
